/**
 * ============================================================================
 * ROOT LAYOUT
 * ============================================================================
 * Server component. Responsibilities:
 *   • load fonts via next/font (self-hosted, zero layout shift)
 *   • mount the theme provider + pre-paint theme bootstrap script
 *   • establish the shared shell: Navbar → main → Footer
 *
 * The layout never re-renders on navigation, so it is the right home for
 * anything that must survive a route change (navbar scroll state, footer).
 */

import type { Metadata, Viewport } from "next";
import { Inter, JetBrains_Mono, Space_Grotesk } from "next/font/google";
import type { ReactNode } from "react";

import "./globals.css";

import { Footer } from "@/components/layout/Footer";
import { Navbar } from "@/components/layout/Navbar";
import {
  PageTransition,
  RouteProgress,
} from "@/components/motion/PageTransition";
import { GlobalCanvas } from "@/components/three/GlobalCanvas";
import { ThemeProvider } from "@/components/theme/ThemeProvider";
import { profile } from "@/data/profile";
import { SITE_URL, absoluteUrl } from "@/lib/site";

/* -------------------------------------------------------------------------
 * Fonts
 * -------------------------------------------------------------------------
 * next/font self-hosts and subsets at build time: no Google request at
 * runtime, no FOIT, and the generated `size-adjust` metrics eliminate the
 * layout shift that `display: swap` normally causes.
 * ------------------------------------------------------------------------- */

/** Body copy. */
const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

/** Headlines. More geometric than Inter, which suits the editorial feel. */
const grotesk = Space_Grotesk({
  subsets: ["latin"],
  variable: "--font-grotesk",
  display: "swap",
});

/** Code blocks and mono UI. */
const mono = JetBrains_Mono({
  subsets: ["latin"],
  variable: "--font-mono-jet",
  display: "swap",
});

/* -------------------------------------------------------------------------
 * Metadata
 * ------------------------------------------------------------------------- */

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),

  /**
   * Title is a template: pages pass their own short title and get
   * "Page · Rizkijack" for free. `default` covers the home page.
   */
  title: {
    default: `${profile.name} — ${profile.tagline[0]}`,
    template: `%s · ${profile.name}`,
  },
  description: profile.shortBio,

  authors: [{ name: profile.name }],
  creator: profile.name,
  publisher: profile.name,

  /**
   * Icons are generated by App Router file conventions, so no binary assets
   * are checked into the repo:
   *   src/app/icon.svg            → favicon
   *   src/app/opengraph-image.tsx → OG card, rasterised to PNG at build time
   *   src/app/manifest.ts         → /manifest.webmanifest
   */
  manifest: "/manifest.webmanifest",

  alternates: { canonical: absoluteUrl("/") },

  openGraph: {
    type: "website",
    locale: "en_US",
    url: absoluteUrl("/"),
    siteName: `${profile.name} — ${profile.tagline[0]}`,
    title: `${profile.name} — ${profile.tagline[0]}`,
    description: profile.shortBio,
  },
  twitter: {
    card: "summary_large_image",
    title: `${profile.name} — ${profile.tagline[0]}`,
    description: profile.shortBio,
  },

  robots: {
    index: true,
    follow: true,
    googleBot: { index: true, follow: true, "max-image-preview": "large" },
  },

  category: "technology",
  keywords: [
    profile.name,
    "personal website",
    "web3",
    "solidity",
    "agentic AI",
    "trader",
    profile.location.country,
  ],
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  // Never cap zoom — capping it is an accessibility failure.
  maximumScale: 5,
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "#f8f7ff" },
    { media: "(prefers-color-scheme: dark)", color: "#0b0b14" },
  ],
  colorScheme: "light dark",
};

/**
 * Runs before first paint so a dark-mode visitor never sees a white flash.
 * Deliberately inline (not a static import): it must execute synchronously,
 * ahead of hydration. Reads the same storage key next-themes uses.
 */
const THEME_BOOTSTRAP = `(function(){try{var k='branding-theme';var s=localStorage.getItem(k);var m=window.matchMedia('(prefers-color-scheme: dark)').matches;var t=(s==='system'||!s)?(m?'dark':'light'):s;var d=document.documentElement;d.classList.remove('light','dark');d.classList.add(t);d.style.colorScheme=t;}catch(e){}})();`;

/* -------------------------------------------------------------------------
 * Component
 * ---------------------------------------------------------------------- */

export default function RootLayout({
  children,
}: Readonly<{ children: ReactNode }>) {
  return (
    // suppressHydrationWarning: the bootstrap script mutates <html> before
    // React hydrates, so its className will never match the server markup.
    <html
      lang="en"
      suppressHydrationWarning
      className={`${inter.variable} ${grotesk.variable} ${mono.variable} h-full`}
    >
      <head>
        <script dangerouslySetInnerHTML={{ __html: THEME_BOOTSTRAP }} />
      </head>

      <body className="flex min-h-full flex-col antialiased">
        <ThemeProvider>
          {/* Skip link — first thing in the tab order, revealed on focus. */}
          <a
            href="#main"
            className="sr-only focus:not-sr-only focus:fixed focus:top-4 focus:left-4 focus:z-100 focus:rounded-pill focus:bg-brand-purple focus:px-5 focus:py-2.5 focus:text-sm focus:font-semibold focus:text-white"
          >
            Skip to content
          </a>

          {/*
            The 3D layer. One WebGL context for the whole site, mounted here so
            it survives every route change. Fixed, full-screen, behind <main>,
            `pointer-events: none` and `aria-hidden` — purely decorative. Also
            the single mount point for `useThreeEnvironment()`, which wires
            scroll / pointer / route / theme / capability signals into the
            store the camera and materials read. Renders a static CSS gradient
            until the client probe resolves, and whenever 3D is off.
          */}
          <GlobalCanvas />

          <Navbar />
          <RouteProgress />

          {/* `grow` pushes the footer down on short pages. */}
          <main id="main" className="grow">
            <PageTransition>{children}</PageTransition>
          </main>

          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
