import type { MetadataRoute } from "next";

import { profile } from "@/data/profile";

/**
 * PWA manifest — /manifest.webmanifest
 *
 * References the app icon generated from `src/app/icon.svg`, so the manifest
 * and the favicon can never drift apart.
 *
 * `start_url` is "/" so the installed app opens on the home page.
 */
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: `${profile.name} — ${profile.tagline[0]}`,
    short_name: profile.name,
    description: profile.shortBio,
    start_url: "/",
    scope: "/",
    display: "standalone",
    orientation: "portrait-primary",
    background_color: "#f7f7f9",
    theme_color: "#8a5cf6",
    categories: ["portfolio", "technology", "personal"],
    icons: [
      {
        src: "/icon.svg",
        sizes: "any",
        type: "image/svg+xml",
        purpose: "any",
      },
      {
        // Generated by src/app/apple-icon.tsx at build time.
        src: "/apple-icon",
        sizes: "180x180",
        type: "image/png",
      },
    ],
  };
}
